class NetworkPartition {
    [String]$DeviceId
    [String]$DeviceName
    [String]$DeviceServiceTag
    [String]$ManagementIpAddress
    [String]$ManagementMacAddress
    [String]$NicId
    [String]$VendorName
    [String]$PortId
    [String]$Model
    [String]$LinkStatus
    [Int]$LinkSpeed
    [String]$Fqdd
    [String]$CurrentMacAddress
    [String]$PermanentMacAddress
    [String]$PermanentFcoeMacAddress
    [String]$VirtualMacAddress
    [String]$VirtualIscsiMacAddress
    [String]$VirtualFipMacAddress
    [String]$NicMode
    [String]$FcoeMode
    [String]$IscsiMode
    [Int]$MinBandwidth
    [Int]$MaxBandwidth
}